# Generated by Django 4.1.7 on 2024-10-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostlyapp', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('house_name', models.CharField(max_length=100)),
                ('post_office', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin_no', models.BigIntegerField()),
                ('sem', models.IntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('parents_phone', models.BigIntegerField()),
                ('photo', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostlyapp.login')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostlyapp.course')),
            ],
        ),
    ]
