# Generated by Django 4.1.7 on 2024-10-11 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostlyapp', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocate_date', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostlyapp.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostlyapp.room')),
            ],
        ),
    ]
