# Generated by Django 4.1.7 on 2024-10-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostlyapp', '0005_room_roomallocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='COURSE',
        ),
    ]
