# Generated by Django 4.1.7 on 2024-10-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlyapp', '0010_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_notification', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
