# Generated by Django 4.1.7 on 2024-10-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlyapp', '0014_rename_room_roomallocation_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallocation',
            name='allocate_date',
            field=models.CharField(max_length=200),
        ),
    ]
