# Generated by Django 4.1.7 on 2024-10-15 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostlyapp', '0015_alter_roomallocation_allocate_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('reported_date', models.CharField(max_length=100)),
                ('resolved_date', models.CharField(max_length=100, null=True)),
                ('student_status', models.CharField(max_length=100)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostlyapp.student')),
            ],
        ),
    ]
