# Generated by Django 4.1.7 on 2024-10-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostlyapp', '0016_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInCheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_out_datetime', models.CharField(max_length=100)),
                ('c_in_datetime', models.CharField(max_length=100, null=True)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostlyapp.student')),
            ],
        ),
    ]
