# Generated by Django 4.1.7 on 2024-10-15 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostlyapp', '0017_checkincheckout'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnTimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_time', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('CHECKINCHECKOUT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostlyapp.checkincheckout')),
            ],
        ),
    ]
