# Generated by Django 3.2.23 on 2024-10-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostlyapp', '0019_alter_room_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='resolved_date',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='status',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='ROOMALLOCATION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostlyapp.roomallocation'),
            preserve_default=False,
        ),
    ]
