# Generated by Django 3.2.23 on 2024-10-21 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostlyapp', '0020_auto_20241019_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='STUDENT',
        ),
        migrations.AddField(
            model_name='attendance',
            name='ROOMALLOCATION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostlyapp.roomallocation'),
            preserve_default=False,
        ),
    ]
