# Generated by Django 3.2.23 on 2024-10-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostlyapp', '0022_auto_20241021_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='month_of_rent',
        ),
    ]
