# Generated by Django 3.2.23 on 2024-10-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostlyapp', '0023_remove_payment_month_of_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='date_of_complaint',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='subject',
        ),
    ]
